name: e2e tests

on:
  workflow_dispatch:
    inputs:
      node_version_file:
        description: 'Passed to setup-node action to specify where to source the version of node from'
        required: false
        type: string
        default: '.nvmrc'
  workflow_call:
    inputs:
      node_version_file:
        description: 'Passed to setup-node action to specify where to source the version of node from'
        required: false
        type: string
        default: '.nvmrc'

permissions:
  contents: read

jobs:
  e2e_test:
    name: Run the e2e tests
    runs-on: [self-hosted, Linux, X64, hmpps-github-actions-runner]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          # Repository is specified to run the workflow from the API repository
          repository: 'ministryofjustice/hmpps-community-payback-ui'

      - name: Use Node.js ${{ inputs.node_version_file }}
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version-file: ${{ inputs.node_version_file }}
          cache: npm

      - name: install dependencies
        shell: bash
        run: |
          npm run setup

      - name: install playwright
        shell: bash
        run: |
          npx playwright install

      - name: run e2e tests
        env:
          ETE_EXTERNAL_API_ENABLED: 'TRUE'
          ETE_EXTERNAL_API_URL: 'https://dev.integration-api.hmpps.service.justice.gov.uk/v1/education/course-completion'
          ETE_EXTERNAL_API_CERT_B64: ${{ secrets.ETE_EXTERNAL_API_CERT_B64 }}
          ETE_EXTERNAL_API_PRIVATE_KEY_B64: ${{ secrets.ETE_EXTERNAL_API_PRIVATE_KEY_B64 }}
          ETE_EXTERNAL_API_API_KEY: ${{ secrets.ETE_EXTERNAL_API_API_KEY }}
          DELIUS_USERNAME: ${{ secrets.DELIUS_USERNAME }}
          DELIUS_PASSWORD: ${{ secrets.DELIUS_PASSWORD }}
          SUPERVISOR_USERNAME: ${{ secrets.SUPERVISOR_USERNAME }}
          SUPERVISOR_PASSWORD: ${{ secrets.SUPERVISOR_PASSWORD }}
          DELIUS_URL: ${{ vars.DELIUS_URL }}
        shell: bash
        run: |
          npm run test:e2e
      - name: upload results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: npm_e2e_test_artifacts
          path: |
            e2e-tests/test_results/
            e2e-tests/playwright-report/

  e2e_test_notify_slack:
    name: 'E2E test failure notification'
    needs: e2e_test
    if: ${{ always() && needs.e2e_test.result == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: ministryofjustice/hmpps-community-payback-ui/.github/actions/slack_failure_notification@9994fccd44456f4b2644908d408478d7c0792264 # main
        with:
          title: 'Community Payback E2E Tests'
          job: 'e2e_test'
          channel_id: ${{ vars.NONPROD_RELEASES_SLACK_CHANNEL }}
          slack_bot_token: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}
